### ISSUE TITLE
Add Brifit T201

### ISSUE THREAD

**Issue by Ernst79** [Bluetooth-Devices/thermobeacon-ble#11]
**Is your feature request related to a problem? Please describe.**
Request/reminder to add Brifit T201

The Brifit Thermometer has a different manufacturer ID (`0xAA55`). but seems to be part of the Thermobeacon family (it is also sold as Oria). In BLE monitor, the Brifit T201 had a different parser (brifit.py), but I have now merged the Thermoplus parser and Brifit parser into a Thermobeacon parser (https://github.com/custom-components/ble_monitor/pull/1079), to be in line with the Thermobeacon integration in HA. 

This issue is to not forget to merge the Brifit T201 into thermobeacon-ble. 

https://github.com/custom-components/ble_monitor/blob/823f9360bcc380ab0eabc6d7f3f1fba9061fd016/custom_components/ble_monitor/ble_parser/thermobeacon.py#L19

**Describe the solution you'd like**

**Additional context**
```
095432303102010614FF55AA0101A4C13874B08501070A1D10F064000100
```
`0954323031` (Name T201)
`020106` (flags)
`14FF55AA` (manufacturer specific data with man. id `0xAA55`
`0101A4C13874B08501070A1D10F064000100` manufacturer specific data (see parser in BLE monitor)

**Comment by bdraco** [comment]
https://github.com/Bluetooth-Devices/sensorpro-ble

Should already be supported by sensorpro

**Comment by Ernst79** [comment]
Ah, sorry, I see. 

They have so many names, still confusing me.
