### ISSUE TITLE
Request support for Thermobeacon WS23 Thermo Hygrometer

### ISSUE THREAD

**Issue by LDIsAGIT** [Bluetooth-Devices/thermobeacon-ble#19]
**Describe the solution you'd like**
Would like support for the new ORIA Thermobeacon (model WS23 upgrade to WS07)

[Amazon link](https://amzn.eu/d/02VK3UvO)

**Additional context**

ThermoBeacon

Device type: LE only
Advertising type: Legacy
Flags: General Discoverable, BrEdrNotSupported
Incomplete List of 16-bit Service UUIDs: 0xFFFO
Manufacturer data (Bluetooth Core 4.1):
Company: ST Microelectronics <0x0030>
0x00008B0100005D44D00B98013803D0490000
Complete Local Name: ThermoBeacon

**Comment by bdraco** [comment]
Please upload diagnostics for the Bluetooth adapter or esphome device

also that Amazon link can’t be shipped to the US

**Comment by bdraco** [comment]
Also please be sure to point out the MAC address of the device in the diagnostics

**Comment by LDIsAGIT** [comment]
Hi

The MAC for the device is - 44:5D:00:00:01:8B 

I believe this is the info you have asked for -

2024-07-03 20:43:40.282 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] epone-fr () [connectable]: <BluetoothServiceInfoBleak name=ThermoBeacon address=44:5D:00:00:01:8B rssi=-74 manufacturer_data={48: b'\x00\x00\x8b\x01\x00\x00]D\xd6\x0bY\x01Y\x03D\x00\x0c\x00'} service_data={} service_uuids=['0000fff0-0000-1000-8000-00805f9b34fb'] 

Scan from phone using nRF connect -
nRF Connect, 2024-07-03
ThermoBeacon (44:5D:00:00:01:8B)
V	21:46:04.498	Connecting to 44:5D:00:00:01:8B...
D	21:46:04.498	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	21:46:20.525	[Callback] Connection state changed with status: 133 and new state: DISCONNECTED (0)
E	21:46:20.526	Error 133 (0x85): GATT ERROR
I	21:46:20.526	Disconnected
D	21:46:43.966	gatt.close()
D	21:46:43.970	wait(200)
V	21:46:44.171	Connecting to 44:5D:00:00:01:8B...
D	21:46:44.171	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	21:46:48.517	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	21:46:48.517	Connected to 44:5D:00:00:01:8B
V	21:46:48.519	Discovering services...
D	21:46:48.519	gatt.discoverServices()
D	21:46:48.568	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
I	21:46:48.784	Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
D	21:46:49.013	[Callback] Services discovered with status: 0
I	21:46:49.013	Services discovered
V	21:46:49.021	Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
- Peripheral Preferred Connection Parameters [R] (0x2A04)
Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
   Client Characteristic Configuration (0x2902)
Device Information (0x180A)
- System ID [R] (0x2A23)
- Model Number String [R] (0x2A24)
- Serial Number String [R] (0x2A25)
- Firmware Revision String [R] (0x2A26)
- Hardware Revision String [R] (0x2A27)
- Software Revision String [R] (0x2A28)
- Manufacturer Name String [R] (0x2A29)
- IEEE 11073-20601 Regulatory Certification Data List [R] (0x2A2A)
- PnP ID [R] (0x2A50)
Unknown Service (0000ffe0-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [W] (0000fff5-0000-1000-8000-00805f9b34fb)
   Characteristic User Description (0x2901)
- Unknown Characteristic [N] (0000fff3-0000-1000-8000-00805f9b34fb)
   Client Characteristic Configuration (0x2902)
   Characteristic User Description (0x2901)
D	21:46:49.022	gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb, true)
D	21:46:49.027	gatt.setCharacteristicNotification(0000fff3-0000-1000-8000-00805f9b34fb, true)
I	21:46:49.112	Connection parameters updated (interval: 30.0ms, latency: 0, timeout: 5000ms)
I	21:46:54.685	Connection parameters updated (interval: 60.0ms, latency: 0, timeout: 5000ms)
V	21:47:39.619	Reading all characteristics...
V	21:47:39.619	Reading characteristic 00002a00-0000-1000-8000-00805f9b34fb
D	21:47:39.619	gatt.readCharacteristic(00002a00-0000-1000-8000-00805f9b34fb)
I	21:47:39.742	Read Response received from 00002a00-0000-1000-8000-00805f9b34fb, value: (0x) 54-68-65-72-6D-6F-42-65-61-63-6F-6E, "ThermoBeacon"
A	21:47:39.742	"ThermoBeacon" received
V	21:47:39.746	Reading characteristic 00002a01-0000-1000-8000-00805f9b34fb
D	21:47:39.746	gatt.readCharacteristic(00002a01-0000-1000-8000-00805f9b34fb)
I	21:47:39.862	Read Response received from 00002a01-0000-1000-8000-00805f9b34fb, value: (0x) 00-00
A	21:47:39.862	"[0] Unknown" received
V	21:47:39.868	Reading characteristic 00002a04-0000-1000-8000-00805f9b34fb
D	21:47:39.868	gatt.readCharacteristic(00002a04-0000-1000-8000-00805f9b34fb)
I	21:47:40.042	Read Response received from 00002a04-0000-1000-8000-00805f9b34fb, value: (0x) 50-00-A0-00-00-00-E8-03
A	21:47:40.042	"Connection Interval: 100.00ms - 200.00ms,
Slave Latency: 0,
Supervision Timeout Multiplier: 1000" received
V	21:47:40.049	Reading characteristic 00002a23-0000-1000-8000-00805f9b34fb
D	21:47:40.049	gatt.readCharacteristic(00002a23-0000-1000-8000-00805f9b34fb)
I	21:47:40.162	Read Response received from 00002a23-0000-1000-8000-00805f9b34fb, value: (0x) 8B-01-00-00-00-00-5D-44
A	21:47:40.162	"(0x) 8B-01-00-00-00-00-5D-44" received
V	21:47:40.168	Reading characteristic 00002a24-0000-1000-8000-00805f9b34fb
D	21:47:40.168	gatt.readCharacteristic(00002a24-0000-1000-8000-00805f9b34fb)
I	21:47:40.343	Read Response received from 00002a24-0000-1000-8000-00805f9b34fb, value: (0x) 4D-6F-64-65-6C-20-4E-75-6D-62-65-72, "Model Number"
A	21:47:40.343	"Model Number" received
V	21:47:40.348	Reading characteristic 00002a25-0000-1000-8000-00805f9b34fb
D	21:47:40.348	gatt.readCharacteristic(00002a25-0000-1000-8000-00805f9b34fb)
I	21:47:40.464	Read Response received from 00002a25-0000-1000-8000-00805f9b34fb, value: (0x) 53-65-72-69-61-6C-20-4E-75-6D-62-65-72, "Serial Number"
A	21:47:40.464	"Serial Number" received
V	21:47:40.470	Reading characteristic 00002a26-0000-1000-8000-00805f9b34fb
D	21:47:40.470	gatt.readCharacteristic(00002a26-0000-1000-8000-00805f9b34fb)
I	21:47:40.642	Read Response received from 00002a26-0000-1000-8000-00805f9b34fb, value: (0x) 46-69-72-6D-77-61-72-65-20-52-65-76-69-73-69-6F-6E, "Firmware Revision"
A	21:47:40.642	"Firmware Revision" received
V	21:47:40.650	Reading characteristic 00002a27-0000-1000-8000-00805f9b34fb
D	21:47:40.650	gatt.readCharacteristic(00002a27-0000-1000-8000-00805f9b34fb)
I	21:47:40.765	Read Response received from 00002a27-0000-1000-8000-00805f9b34fb, value: (0x) 48-61-72-64-77-61-72-65-20-52-65-76-69-73-69-6F-6E, "Hardware Revision"
A	21:47:40.765	"Hardware Revision" received
V	21:47:40.773	Reading characteristic 00002a28-0000-1000-8000-00805f9b34fb
D	21:47:40.773	gatt.readCharacteristic(00002a28-0000-1000-8000-00805f9b34fb)
I	21:47:40.888	Read Response received from 00002a28-0000-1000-8000-00805f9b34fb, value: (0x) 53-6F-66-74-77-61-72-65-20-52-65-76-69-73-69-6F-6E, "Software Revision"
A	21:47:40.888	"Software Revision" received
V	21:47:40.894	Reading characteristic 00002a29-0000-1000-8000-00805f9b34fb
D	21:47:40.894	gatt.readCharacteristic(00002a29-0000-1000-8000-00805f9b34fb)
I	21:47:41.004	Read Response received from 00002a29-0000-1000-8000-00805f9b34fb, value: (0x) 4D-61-6E-75-66-61-63-74-75-72-65-72-20-4E-61-6D-65, "Manufacturer Name"
A	21:47:41.005	"Manufacturer Name" received
V	21:47:41.010	Reading characteristic 00002a2a-0000-1000-8000-00805f9b34fb
D	21:47:41.010	gatt.readCharacteristic(00002a2a-0000-1000-8000-00805f9b34fb)
I	21:47:41.127	Read Response received from 00002a2a-0000-1000-8000-00805f9b34fb, value: (0x) FE-00-65-78-70-65-72-69-6D-65-6E-74-61-6C
A	21:47:41.127	"(0x) FE-00-65-78-70-65-72-69-6D-65-6E-74-61-6C" received
V	21:47:41.133	Reading characteristic 00002a50-0000-1000-8000-00805f9b34fb
D	21:47:41.133	gatt.readCharacteristic(00002a50-0000-1000-8000-00805f9b34fb)
I	21:47:41.246	Read Response received from 00002a50-0000-1000-8000-00805f9b34fb, value: (0x) 01-04-05-00-00-10-01
A	21:47:41.246	"Bluetooth SIG Company: PHYPLUS Inc <0x0504>
Product Id: 0
Product Version: 272" received
V	21:47:41.246	12 characteristics read

**Comment by LDIsAGIT** [comment]
Hi

The MAC for the device is - 44:5D:00:00:01:8B 

I believe this is the info you have asked for -

2024-07-03 20:43:40.282 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] epone-fr () [connectable]: <BluetoothServiceInfoBleak name=ThermoBeacon address=44:5D:00:00:01:8B rssi=-74 manufacturer_data={48: b'\x00\x00\x8b\x01\x00\x00]D\xd6\x0bY\x01Y\x03D\x00\x0c\x00'} service_data={} service_uuids=['0000fff0-0000-1000-8000-00805f9b34fb'] 

Scan from phone using nRF connect -
nRF Connect, 2024-07-03
ThermoBeacon (44:5D:00:00:01:8B)
V	21:46:04.498	Connecting to 44:5D:00:00:01:8B...
D	21:46:04.498	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	21:46:20.525	[Callback] Connection state changed with status: 133 and new state: DISCONNECTED (0)
E	21:46:20.526	Error 133 (0x85): GATT ERROR
I	21:46:20.526	Disconnected
D	21:46:43.966	gatt.close()
D	21:46:43.970	wait(200)
V	21:46:44.171	Connecting to 44:5D:00:00:01:8B...
D	21:46:44.171	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	21:46:48.517	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	21:46:48.517	Connected to 44:5D:00:00:01:8B
V	21:46:48.519	Discovering services...
D	21:46:48.519	gatt.discoverServices()
D	21:46:48.568	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
I	21:46:48.784	Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
D	21:46:49.013	[Callback] Services discovered with status: 0
I	21:46:49.013	Services discovered
V	21:46:49.021	Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
- Peripheral Preferred Connection Parameters [R] (0x2A04)
Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
   Client Characteristic Configuration (0x2902)
Device Information (0x180A)
- System ID [R] (0x2A23)
- Model Number String [R] (0x2A24)
- Serial Number String [R] (0x2A25)
- Firmware Revision String [R] (0x2A26)
- Hardware Revision String [R] (0x2A27)
- Software Revision String [R] (0x2A28)
- Manufacturer Name String [R] (0x2A29)
- IEEE 11073-20601 Regulatory Certification Data List [R] (0x2A2A)
- PnP ID [R] (0x2A50)
Unknown Service (0000ffe0-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [W] (0000fff5-0000-1000-8000-00805f9b34fb)
   Characteristic User Description (0x2901)
- Unknown Characteristic [N] (0000fff3-0000-1000-8000-00805f9b34fb)
   Client Characteristic Configuration (0x2902)
   Characteristic User Description (0x2901)
D	21:46:49.022	gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb, true)
D	21:46:49.027	gatt.setCharacteristicNotification(0000fff3-0000-1000-8000-00805f9b34fb, true)
I	21:46:49.112	Connection parameters updated (interval: 30.0ms, latency: 0, timeout: 5000ms)
I	21:46:54.685	Connection parameters updated (interval: 60.0ms, latency: 0, timeout: 5000ms)
V	21:47:39.619	Reading all characteristics...
V	21:47:39.619	Reading characteristic 00002a00-0000-1000-8000-00805f9b34fb
D	21:47:39.619	gatt.readCharacteristic(00002a00-0000-1000-8000-00805f9b34fb)
I	21:47:39.742	Read Response received from 00002a00-0000-1000-8000-00805f9b34fb, value: (0x) 54-68-65-72-6D-6F-42-65-61-63-6F-6E, "ThermoBeacon"
A	21:47:39.742	"ThermoBeacon" received
V	21:47:39.746	Reading characteristic 00002a01-0000-1000-8000-00805f9b34fb
D	21:47:39.746	gatt.readCharacteristic(00002a01-0000-1000-8000-00805f9b34fb)
I	21:47:39.862	Read Response received from 00002a01-0000-1000-8000-00805f9b34fb, value: (0x) 00-00
A	21:47:39.862	"[0] Unknown" received
V	21:47:39.868	Reading characteristic 00002a04-0000-1000-8000-00805f9b34fb
D	21:47:39.868	gatt.readCharacteristic(00002a04-0000-1000-8000-00805f9b34fb)
I	21:47:40.042	Read Response received from 00002a04-0000-1000-8000-00805f9b34fb, value: (0x) 50-00-A0-00-00-00-E8-03
A	21:47:40.042	"Connection Interval: 100.00ms - 200.00ms,
Slave Latency: 0,
Supervision Timeout Multiplier: 1000" received
V	21:47:40.049	Reading characteristic 00002a23-0000-1000-8000-00805f9b34fb
D	21:47:40.049	gatt.readCharacteristic(00002a23-0000-1000-8000-00805f9b34fb)
I	21:47:40.162	Read Response received from 00002a23-0000-1000-8000-00805f9b34fb, value: (0x) 8B-01-00-00-00-00-5D-44
A	21:47:40.162	"(0x) 8B-01-00-00-00-00-5D-44" received
V	21:47:40.168	Reading characteristic 00002a24-0000-1000-8000-00805f9b34fb
D	21:47:40.168	gatt.readCharacteristic(00002a24-0000-1000-8000-00805f9b34fb)
I	21:47:40.343	Read Response received from 00002a24-0000-1000-8000-00805f9b34fb, value: (0x) 4D-6F-64-65-6C-20-4E-75-6D-62-65-72, "Model Number"
A	21:47:40.343	"Model Number" received
V	21:47:40.348	Reading characteristic 00002a25-0000-1000-8000-00805f9b34fb
D	21:47:40.348	gatt.readCharacteristic(00002a25-0000-1000-8000-00805f9b34fb)
I	21:47:40.464	Read Response received from 00002a25-0000-1000-8000-00805f9b34fb, value: (0x) 53-65-72-69-61-6C-20-4E-75-6D-62-65-72, "Serial Number"
A	21:47:40.464	"Serial Number" received
V	21:47:40.470	Reading characteristic 00002a26-0000-1000-8000-00805f9b34fb
D	21:47:40.470	gatt.readCharacteristic(00002a26-0000-1000-8000-00805f9b34fb)
I	21:47:40.642	Read Response received from 00002a26-0000-1000-8000-00805f9b34fb, value: (0x) 46-69-72-6D-77-61-72-65-20-52-65-76-69-73-69-6F-6E, "Firmware Revision"
A	21:47:40.642	"Firmware Revision" received
V	21:47:40.650	Reading characteristic 00002a27-0000-1000-8000-00805f9b34fb
D	21:47:40.650	gatt.readCharacteristic(00002a27-0000-1000-8000-00805f9b34fb)
I	21:47:40.765	Read Response received from 00002a27-0000-1000-8000-00805f9b34fb, value: (0x) 48-61-72-64-77-61-72-65-20-52-65-76-69-73-69-6F-6E, "Hardware Revision"
A	21:47:40.765	"Hardware Revision" received
V	21:47:40.773	Reading characteristic 00002a28-0000-1000-8000-00805f9b34fb
D	21:47:40.773	gatt.readCharacteristic(00002a28-0000-1000-8000-00805f9b34fb)
I	21:47:40.888	Read Response received from 00002a28-0000-1000-8000-00805f9b34fb, value: (0x) 53-6F-66-74-77-61-72-65-20-52-65-76-69-73-69-6F-6E, "Software Revision"
A	21:47:40.888	"Software Revision" received
V	21:47:40.894	Reading characteristic 00002a29-0000-1000-8000-00805f9b34fb
D	21:47:40.894	gatt.readCharacteristic(00002a29-0000-1000-8000-00805f9b34fb)
I	21:47:41.004	Read Response received from 00002a29-0000-1000-8000-00805f9b34fb, value: (0x) 4D-61-6E-75-66-61-63-74-75-72-65-72-20-4E-61-6D-65, "Manufacturer Name"
A	21:47:41.005	"Manufacturer Name" received
V	21:47:41.010	Reading characteristic 00002a2a-0000-1000-8000-00805f9b34fb
D	21:47:41.010	gatt.readCharacteristic(00002a2a-0000-1000-8000-00805f9b34fb)
I	21:47:41.127	Read Response received from 00002a2a-0000-1000-8000-00805f9b34fb, value: (0x) FE-00-65-78-70-65-72-69-6D-65-6E-74-61-6C
A	21:47:41.127	"(0x) FE-00-65-78-70-65-72-69-6D-65-6E-74-61-6C" received
V	21:47:41.133	Reading characteristic 00002a50-0000-1000-8000-00805f9b34fb
D	21:47:41.133	gatt.readCharacteristic(00002a50-0000-1000-8000-00805f9b34fb)
I	21:47:41.246	Read Response received from 00002a50-0000-1000-8000-00805f9b34fb, value: (0x) 01-04-05-00-00-10-01
A	21:47:41.246	"Bluetooth SIG Company: PHYPLUS Inc <0x0504>
Product Id: 0
Product Version: 272" received
V	21:47:41.246	12 characteristics read
